#!/bin/bash

source_dir="./files"

for file in "$source_dir"/*; 
	do
	first_char=$(basename "$file" | cut -c 1 | tr '[:upper:]' '[:lower:]')
	#echo "$first_char"
	dest_dir="./$first_char"
	mv "$file" "$dest_dir"
	#echo "Moved $file to $dest_dir"
done
